import React, { useState, useEffect } from 'react';
import { resolveImageSrc, getCachedImageSrc } from '../../services/imageStorageService';

export interface MarkdownImageProps {
  src?: string;
  alt?: string;
  title?: string;
  onOpenLightbox: (data: { src: string; alt?: string; title?: string }) => void;
  [key: string]: any;
}

export const MarkdownImage: React.FC<MarkdownImageProps> = ({
  src = '',
  alt,
  title,
  onOpenLightbox,
  ...props
}) => {
  // Pass through rich visual icon images generated by replaceRichIconsInReactNode
  if (props.className?.includes('apple-emoji') || props.className?.includes('rich-icon')) {
    return <img src={src} alt={alt} {...props} />;
  }

  const [resolvedSrc, setResolvedSrc] = useState<string>(() => {
    return getCachedImageSrc(src) || src;
  });
  const [isLoading, setIsLoading] = useState<boolean>(() => {
    if (src.startsWith('image://') || src.startsWith('img_')) {
      return !getCachedImageSrc(src);
    }
    return false;
  });

  useEffect(() => {
    if (!src) return;
    if (src.startsWith('image://') || src.startsWith('img_')) {
      let isMounted = true;
      resolveImageSrc(src).then((res) => {
        if (isMounted) {
          setResolvedSrc(res);
          setIsLoading(false);
        }
      });
      return () => {
        isMounted = false;
      };
    } else {
      setResolvedSrc(src);
      setIsLoading(false);
    }
  }, [src]);

  if (isLoading) {
    return (
      <figure className="my-5 inline-block max-w-full">
        <div className="w-64 h-36 rounded-2xl bg-neutral-100 dark:bg-neutral-800 animate-pulse flex items-center justify-center text-xs text-neutral-400 border border-neutral-200 dark:border-neutral-800">
          Loading image...
        </div>
      </figure>
    );
  }

  return (
    <figure className="my-5 inline-block max-w-full">
      <img
        src={resolvedSrc}
        alt={alt || 'Embedded Markdown image'}
        title={title}
        loading="lazy"
        onClick={() => onOpenLightbox({ src: resolvedSrc, alt, title })}
        className="rounded-2xl border border-neutral-200/80 dark:border-neutral-800 shadow-sm max-w-full h-auto max-h-[550px] object-contain cursor-zoom-in hover:opacity-95 transition-all bg-neutral-50 dark:bg-neutral-900"
        onError={(e) => {
          const target = e.currentTarget;
          target.style.display = 'none';
          const parent = target.parentElement;
          if (parent && !parent.querySelector('.img-error-fallback')) {
            const fallback = document.createElement('div');
            fallback.className = 'img-error-fallback p-3 rounded-xl border border-dashed border-rose-300 dark:border-rose-900 bg-rose-50/50 dark:bg-rose-950/30 text-xs text-rose-600 dark:text-rose-400 flex items-center gap-2';
            const span = document.createElement('span');
            span.textContent = `⚠️ Could not load image: ${alt || src}`;
            fallback.appendChild(span);
            parent.appendChild(fallback);
          }
        }}
        {...props}
      />
      {title && (
        <figcaption className="text-center text-xs text-neutral-500 dark:text-neutral-400 mt-2 italic">
          {title}
        </figcaption>
      )}
    </figure>
  );
};
